/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffaaf6",
        "inverse-on-surface": "#2f3038",
        tertiary: "#ffaceb",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#390034",
        "secondary-fixed": "#b4ebff",
        "surface-container-low": "#1a1b22",
        "tertiary-fixed-dim": "#ffaceb",
        "surface-container-high": "#292931",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#800083",
        "primary-fixed": "#ffd7f6",
        "on-secondary-fixed-variant": "#004e5f",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c8c4d7",
        "secondary-container": "#00d2fd",
        primary: "#ffaaf6",
        "inverse-surface": "#e3e1ec",
        "on-secondary": "#003642",
        "tertiary-container": "#cd26bc",
        "on-primary": "#5b005d",
        "on-primary-container": "#fffeff",
        "on-primary-fixed": "#380039",
        "on-tertiary-fixed-variant": "#830079",
        secondary: "#a2e7ff",
        outline: "#928ea1",
        surface: "#12131a",
        "inverse-primary": "#a800ac",
        "surface-dim": "#12131a",
        "on-surface": "#e3e1ec",
        "surface-variant": "#33343c",
        "primary-container": "#c62dc8",
        "on-background": "#e3e1ec",
        "surface-container": "#1e1f26",
        "error-container": "#93000a",
        "surface-tint": "#ffaaf6",
        "surface-container-highest": "#33343c",
        "on-tertiary-container": "#fffeff",
        "surface-bright": "#383941",
        "secondary-fixed-dim": "#3cd7ff",
        background: "#12131a",
        "on-secondary-container": "#005669",
        "surface-container-lowest": "#0d0e15",
        "on-secondary-fixed": "#001f27",
        "outline-variant": "#474555",
        "tertiary-fixed": "#ffd7f2",
        "on-tertiary": "#5d0055"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "3xl": "64px",
        unit: "4px",
        xl: "32px",
        sm: "8px",
        lg: "24px",
        "sidebar-width": "280px",
        "container-max": "1440px",
        "2xl": "48px",
        md: "16px",
        xs: "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Sora"],
        "headline-lg": ["Sora"],
        "body-lg": ["Inter"],
        "headline-md": ["Sora"],
        "display-lg": ["Sora"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Sora"],
        "body-sm": ["Inter"],
        headline: ["Sora"],
        display: ["Sora"],
        body: ["Inter"],
        label: ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {lineHeight: "1.2", fontWeight: "600"}],
        "headline-lg": ["32px", {lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600"}],
        "body-lg": ["18px", {lineHeight: "1.6", fontWeight: "400"}],
        "headline-md": ["24px", {lineHeight: "1.3", fontWeight: "600"}],
        "display-lg": ["48px", {lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700"}],
        "body-md": ["16px", {lineHeight: "1.5", fontWeight: "400"}],
        "label-md": ["12px", {lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500"}],
        "headline-sm": ["20px", {lineHeight: "1.4", fontWeight: "500"}],
        "body-sm": ["14px", {lineHeight: "1.5", fontWeight: "400"}]
      }
    }
  },
  plugins: [],
}

